services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: reservams-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: reservams-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: reservams-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8095:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: reservams-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  reservams-eureka-server:
    build:
      context: ../reservams-eureka-server
    container_name: reservams-eureka-server
    ports:
      - "8761:8761"

  reservams-api-gateway:
    build:
      context: ../reservams-api-gateway
    container_name: reservams-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - reservams-eureka-server
    command:
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"

  reservams-auth-service:
    build:
      context: ../reservams-auth-service
    container_name: reservams-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - reservams-eureka-server
    command:
      - "--spring.profiles.active=prod"
      - "--DB_URL=jdbc:mysql://host.docker.internal:3306/reservams_auth_db"
      - "--DB_USERNAME=root"
      - "--DB_PASSWORD="
      - "--EUREKA_URL=http://reservams-eureka-server:8761/eureka/"
      - "--JWT_SECRET=reservamsSecretKeyForJwt2026Minimo32Characters"
      - "--JWT_EXPIRATION=86400000"

  reservams-user-service:
    build:
      context: ../reservams-user-service
    container_name: reservams-user-service
    ports:
      - "8082:8082"
    depends_on:
      - reservams-eureka-server
    command:
      - "--spring.profiles.active=prod"
      - "--spring.datasource.url=jdbc:mysql://host.docker.internal:3306/reservams_user_db"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password="
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"

  reservams-hotel-service:
    build:
      context: ../reservams-hotel-service
    container_name: reservams-hotel-service
    ports:
      - "8083:8083"
    depends_on:
      - reservams-eureka-server
    command:
      - "--spring.profiles.active=prod"
      - "--DB_URL=jdbc:mysql://host.docker.internal:3306/reservams_hotel_db"
      - "--DB_USERNAME=root"
      - "--DB_PASSWORD="
      - "--EUREKA_URL=http://reservams-eureka-server:8761/eureka/"

  reservams-room-service:
    build:
      context: ../reservams-room-service
    container_name: reservams-room-service
    ports:
      - "8084:8084"
    depends_on:
      - reservams-eureka-server
      - reservams-hotel-service
    command:
        - "--spring.profiles.active=prod"
        - "--DB_URL=jdbc:mysql://host.docker.internal:3306/reservams_room_db"
        - "--DB_USERNAME=root"
        - "--DB_PASSWORD="
        - "--EUREKA_URL=http://reservams-eureka-server:8761/eureka/"
        - "--HOTEL_SERVICE_URL=http://reservams-hotel-service:8083"

  reservams-availability-service:
    build:
      context: ../reservams-availability-service
    container_name: reservams-availability-service
    ports:
      - "8085:8085"
    depends_on:
      - reservams-eureka-server
    command:
      - "--spring.profiles.active=prod"
      - "--DB_URL=jdbc:mysql://host.docker.internal:3306/reservams_availability_db"
      - "--DB_USERNAME=root"
      - "--DB_PASSWORD="
      - "--EUREKA_URL=http://reservams-eureka-server:8761/eureka/"

  reservams-reservation-service:
    build:
      context: ../reservams-reservation-service
    container_name: reservams-reservation-service
    ports:
      - "8086:8086"
    depends_on:
      - reservams-eureka-server
      - kafka
      - reservams-user-service
      - reservams-room-service
      - reservams-availability-service
    command:
      - "--spring.profiles.active=prod"
      - "--DB_URL=jdbc:mysql://host.docker.internal:3306/reservams_reservation_db"
      - "--DB_USERNAME=root"
      - "--DB_PASSWORD="
      - "--EUREKA_URL=http://reservams-eureka-server:8761/eureka/"
      - "--KAFKA_BOOTSTRAP_SERVERS=kafka:29092"
      - "--AVAILABILITY_SERVICE_URL=http://reservams-availability-service:8085"

  reservams-payment-service:
    build:
      context: ../reservams-payment-service
    container_name: reservams-payment-service
    ports:
      - "8087:8087"
    depends_on:
      - reservams-eureka-server
      - reservams-reservation-service
    command:
      - "--spring.datasource.url=jdbc:mysql://host.docker.internal:3306/reservams_payment_db"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password="
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"
      - "--reservation.service.url=http://reservams-reservation-service:8086"

  reservams-notification-service:
    build:
      context: ../reservams-notification-service
    container_name: reservams-notification-service
    ports:
      - "8088:8088"
    depends_on:
      - reservams-eureka-server
      - kafka
    command:
      - "--spring.datasource.url=jdbc:mysql://host.docker.internal:3306/reservams_notification_db"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password="
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"
      - "--spring.kafka.bootstrap-servers=kafka:29092"

  reservams-review-service:
    build:
      context: ../reservams-review-service
    container_name: reservams-review-service
    ports:
      - "8089:8089"
    depends_on:
      - reservams-eureka-server
      - reservams-reservation-service
    command:
      - "--spring.datasource.url=jdbc:mysql://host.docker.internal:3306/reservams_review_db"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password="
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"
      - "--reservation.service.url=http://reservams-reservation-service:8086"

  reservams-report-service:
    build:
      context: ../reservams-report-service
    container_name: reservams-report-service
    ports:
      - "8090:8090"
    depends_on:
      - reservams-eureka-server
    command:
      - "--spring.datasource.url=jdbc:mysql://host.docker.internal:3306/reservams_report_db"
      - "--spring.datasource.username=root"
      - "--spring.datasource.password="
      - "--eureka.client.service-url.defaultZone=http://reservams-eureka-server:8761/eureka/"